server:
  port: ${SERVER_PORT:9096}
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://${SERVER_URL:localhost}:3306/authorization_svc?useUnicode=yes&characterEncoding=UTF-8}
    driver-class-name: ${DB_DRIVER_CLASS:com.mysql.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    show-sql: true
  flyway:
    locations: classpath:/db/migration
oauth2:
  jwt:
    jks: classpath:jwt.jks
    keypair: ${JWT_KEYPAIR:jwt}
    keypass: ${JWT_KEYPASS:P@ssword}
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SVC_DISCOVERY:http://user:password@${SERVER_URL:localhost}:9091/eureka/}
---
spring:
  profiles: test
  datasource:
    url: ${DB_URL:jdbc:h2:mem:users;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: ${DB_DRIVER_CLASS:org.h2.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  jpa:
    show-sql: true
  flyway:
    locations: classpath:/db/migration