spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://${SERVER_URL:localhost}:3306/customer_svc?useUnicode=yes&characterEncoding=UTF-8}
    driver-class-name: ${DB_DRIVER_CLASS:com.mysql.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    show-sql: true
  rabbitmq:
    host: ${RABBIT_QUEUE_HOST:localhost}
    port: ${RABBIT_QUEUE_PORT:5672}
    username: ${RABBIT_QUEUE_USER:admin}
    password: ${RABIIT_QUEUE_PASS:admin}
flyway:
  enabled: true
  locations: classpath:/db/migration
  schemas: customer_svc
server:
  port: ${SERVER_PORT:9093}
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SVC_DISCOVERY:http://user:password@${SERVER_URL:localhost}:9091/eureka/}
customer:
  svc:
    queue: ${RABBIT_QUEUE_NAME:CUSTOMER-SVC}
---
spring:
  profiles: test
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/customer_svc?useUnicode=yes&characterEncoding=UTF-8}
    driver-class-name: ${DB_DRIVER_CLASS:com.mysql.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  jpa:
    show-sql: true