spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://${SERVER_URL:localhost}:3306/customer_svc?useUnicode=yes&characterEncoding=UTF-8}
    driver-class-name: ${DB_DRIVER_CLASS:com.mysql.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    show-sql: true
  flyway:
      enabled: true
      locations: classpath:/db/migration
      schemas: customer_svc
  activemq:
    broker-url: ${ACTIVEMQ_URL:tcp://${SERVER_URL:localhost}:61616}
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASS:admin}
  jms:
    listener:
      auto-startup: true
server:
  port: ${SERVER_PORT:9093}
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SVC_DISCOVERY:http://user:password@${SERVER_URL:localhost}:9091/eureka/}
customer:
  svc:
    queue: ${RABBIT_QUEUE_NAME:CUSTOMER-SVC}
oauth2:
  jwt:
    public:
      key:
        -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkcm7qS7RZfrdMLIVgQQA
          bFKORsnatz3Bihl2ZJStG7gWfqdewaWEMG0vasBj+LHF+6FSfQjF6C0iVn/21O10
          RBZ0hfLr/K9nEMVLof+LtxR9UeHec45MA7FKgr1UYKazaaasas4QdvPN0XXxEY6b
          ZbLJQmV56wtFAzT1+p+S3S1105AvZJjE+GSXljweF4bpRERnmD41IaLOVFl8+N1o
          mztf4yDhK7zglaSveLVto7dx4/8kFLmJaw/Zqmy6ji9fL/tuq41bP4Cu1/oboQLd
          iqaYE/nhKW3UzalZGLSsAlDV6wsl7Yp8LCsuO/aa5IOxt/NB08SEgDXEn9XABNbc
          jwIDAQAB
        -----END PUBLIC KEY-----
---
spring:
  profiles: test
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/customer_svc?useUnicode=yes&characterEncoding=UTF-8}
    driver-class-name: ${DB_DRIVER_CLASS:com.mysql.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration