spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://localhost:27017/message-svc}
server:
  port: ${SERVER_PORT:9092}
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SVC_DISCOVERY:http://user:password@localhost:9091/eureka/}