spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://localhost:27017/message-svc}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASS:admin}
server:
  port: ${SERVER_PORT:9092}
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SVC_DISCOVERY:http://user:password@localhost:9091/eureka/}
message:
  svc:
    queue: ${MESSAGE_QUEUE:MESSAGE-QUEUE}
customer:
  svc:
    queue: ${MESSAGE_QUEUE:CUSTOMER-QUEUE}